name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
       xmake-version: '2.9.8'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.9
      with:
        name: my-build-output
        path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
